url: https://m-umar.me
title: MUS
description: The Archives of M. Umar Shahbaz
author: M. Umar Shahbaz
logo: /assets/img/icon.png

collections:
  pages:
    output: true
  projects:
    output: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-imagemagick
  - jekyll-minifier
  - jekyll-terser

imagemagick:
  enabled: true
  widths:
    - 480
    - 800
    - 1400
  input_directories:
    - assets/img/
  input_formats:
    - ".jpg"
    - ".jpeg"
    - ".png"
    - ".tiff"
    - ".gif"
  output_formats:
    webp: "-quality 85"

lazy_loading_images: true

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

jekyll-minifier:
  compress_javascript: false

terser:
  compress:
    drop_console: true