url: "https://m-umar.me"
baseurl: "/preview"
title: MUS
description: The Archives of M. Umar Shahbaz
author: M. Umar Shahbaz
image: /assets/img/original/icon.png
logo: /assets/img/original/icon.png

collections:
  navbar_pages:
    output: true
  projects:
    output: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-minifier
  - jekyll-terser
  - jekyll_dynamic_assets
  - jekyll_picture_tag

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: "highlight"
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

jekyll-minifier:
  compress_javascript: false

terser:
  compress:
    drop_console: true

picture:
  source: "assets/img/original"
  output: "assets/img/"
  suppress_warnings: true
  relative: false
  fast_build: true

exclude:
  - .bundle/
  - .gitignore
  - .github/
  - .jekyll-cache/
  - .vscode/
  - docker_build/
  - .dockerignore
  - Dockerfile
  - Gemfile
  - Gemfile.lock

dynamic_assets:
  absolute: true
  master:
   - master.css
   - aos.min.js::defer-js
   - bootstrap.min.js::defer-js
   - fuse.min.js::defer-js
  formats:
    defer-js: <script defer src="%s"></script>