url: https://m-umar.me
baseurl: /
title: MUS
description: The Archives of M. Umar Shahbaz
author: M. Umar Shahbaz

collections:
  pages:
    output: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag